services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=bookstore'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'
    hostname: localhost
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge